#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMPdfAnnotation.h"
@protocol CMPdfAnnotation;
@class CMPdfAnnotation;



@protocol CMAddPdfAnnotationRequest
@end

@interface CMAddPdfAnnotationRequest : CMObject

/* Input file contents bytes for the file to modify [optional]
 */
@property(nonatomic) NSData* inputFileBytes;
/* Annotations to add to the PDF file [optional]
 */
@property(nonatomic) NSArray<CMPdfAnnotation>* annotationsToAdd;

@end
