#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMAlternateFileFormatCandidate
@end

@interface CMAlternateFileFormatCandidate : CMObject

/* Probability that this extension is the right one; possible values are between 0.0 (lowest confidence) and 1.0 (highest confidence) [optional]
 */
@property(nonatomic) NSNumber* probability;
/* Detected file extension of the file format, with a leading period [optional]
 */
@property(nonatomic) NSString* detectedFileExtension;
/* MIME type of this file extension [optional]
 */
@property(nonatomic) NSString* detectedMimeType;

@end
