#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMBase64DecodeRequest
@end

@interface CMBase64DecodeRequest : CMObject

/* Input content to decode from Base 64 into binary [optional]
 */
@property(nonatomic) NSString* base64ContentToDecode;

@end
