#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMBase64EncodeRequest
@end

@interface CMBase64EncodeRequest : CMObject

/* Input content to encode into Base 64 [optional]
 */
@property(nonatomic) NSData* contentToEncode;

@end
