#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMBase64DetectRequest
@end

@interface CMBase64DetectRequest : CMObject

/* Input content text to detect if it is base 64 encoded [optional]
 */
@property(nonatomic) NSString* base64ContentToDetect;

@end
