#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMBase64EncodeResponse
@end

@interface CMBase64EncodeResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Result of performing a base 64 encoding operation, a text string representing the encoded original file content [optional]
 */
@property(nonatomic) NSString* base64TextContentResult;

@end
