#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMConvertedJpgPage
@end

@interface CMConvertedJpgPage : CMObject

/* Page number of the converted page, starting with 1 [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* The JPG file of this page as a byte array [optional]
 */
@property(nonatomic) NSData* content;

@end
