#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMXlsxSpreadsheetRow.h"
@protocol CMXlsxSpreadsheetRow;
@class CMXlsxSpreadsheetRow;



@protocol CMCreateSpreadsheetFromDataRequest
@end

@interface CMCreateSpreadsheetFromDataRequest : CMObject

/* Optional; The new Spreadsheet will have a default Worksheet in it; supply a name, or if left empty, will default to Worksheet1 [optional]
 */
@property(nonatomic) NSString* worksheetName;
/* Required; Rows and cells to populate the spreadsheet with [optional]
 */
@property(nonatomic) NSArray<CMXlsxSpreadsheetRow>* rows;

@end
