#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMCreateBlankSpreadsheetRequest
@end

@interface CMCreateBlankSpreadsheetRequest : CMObject

/* The blank Spreadsheet will have a default Worksheet in it; supply a name, or if left empty, will default to Worksheet1 [optional]
 */
@property(nonatomic) NSString* worksheetName;

@end
