#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMCsvFileResult
@end

@interface CMCsvFileResult : CMObject

/* Title of the CSV file [optional]
 */
@property(nonatomic) NSString* title;
/* Contents of the CSV file [optional]
 */
@property(nonatomic) NSData* fileContents;

@end
