#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMCsvFileResult.h"
@protocol CMCsvFileResult;
@class CMCsvFileResult;



@protocol CMCsvCollection
@end

@interface CMCsvCollection : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Array of CSV File results [optional]
 */
@property(nonatomic) NSArray<CMCsvFileResult>* csvFiles;
/* Count of the number of CSV files produced [optional]
 */
@property(nonatomic) NSNumber* fileCount;

@end
