#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDetectLineEndingsResponse
@end

@interface CMDetectLineEndingsResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Type of newline in the file; possible vlaues are \"Mac\" (legacy Mac OS uses carriage return only); \"Unix\" (Unix and Linux OSes, and modern Mac OS); \"Windows\" (Windows operating systems) [optional]
 */
@property(nonatomic) NSString* primaryNewlineType;
/* Characters used to terminate a newline; can be carriage return, linefeed, or carriage return + linefeed [optional]
 */
@property(nonatomic) NSString* primaryNewlineTerminator;
/* Length of the input string in characters [optional]
 */
@property(nonatomic) NSNumber* inputLength;

@end
