#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDeleteDocxTableRowRangeRequest
@end

@interface CMDeleteDocxTableRowRangeRequest : CMObject

/* Optional: Bytes of the input file to operate on [optional]
 */
@property(nonatomic) NSData* inputFileBytes;
/* Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). [optional]
 */
@property(nonatomic) NSString* inputFileUrl;
/* Path to the table to delete the row from [optional]
 */
@property(nonatomic) NSString* tablePath;
/* 0-based index of the row to begin deleting rows (e.g. 0, 1, 2, ...) in the table [optional]
 */
@property(nonatomic) NSNumber* tableRowRowIndexStart;
/* 0-based index of the row to stop deleting rows (e.g. 0, 1, 2, ...) in the table [optional]
 */
@property(nonatomic) NSNumber* tableRowRowIndexEnd;

@end
