#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxParagraph.h"
#import "CMDocxSection.h"
@protocol CMDocxParagraph;
@class CMDocxParagraph;
@protocol CMDocxSection;
@class CMDocxSection;



@protocol CMDocxFooter
@end

@interface CMDocxFooter : CMObject

/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* Paragraphs in this footer [optional]
 */
@property(nonatomic) NSArray<CMDocxParagraph>* paragraphs;
/* Sections that the footer is applied to [optional]
 */
@property(nonatomic) NSArray<CMDocxSection>* sectionsWithFooter;

@end
