#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxStyle
@end

@interface CMDocxStyle : CMObject

/* ID of the style [optional]
 */
@property(nonatomic) NSString* styleID;
/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* Style applies bold formatting [optional]
 */
@property(nonatomic) NSNumber* bold;
/* Style applies italic formatting [optional]
 */
@property(nonatomic) NSNumber* italic;
/* Style applies underline formatting [optional]
 */
@property(nonatomic) NSNumber* underline;
/* Font size [optional]
 */
@property(nonatomic) NSString* fontSize;
/* Font family [optional]
 */
@property(nonatomic) NSString* fontFamily;

@end
