#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxText
@end

@interface CMDocxText : CMObject

/* Index of the text content in the run; 0-based [optional]
 */
@property(nonatomic) NSNumber* textIndex;
/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* Text string containing the text content of this text content item [optional]
 */
@property(nonatomic) NSString* textContent;

@end
