#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxParagraph.h"
@protocol CMDocxParagraph;
@class CMDocxParagraph;



@protocol CMDocxPage
@end

@interface CMDocxPage : CMObject

/* Page number of this page, 1-based [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* All paragraphs anywhere in the document; these objects are not sequentially placed but are scatted across document [optional]
 */
@property(nonatomic) NSArray<CMDocxParagraph>* paragraphs;

@end
