#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxSection
@end

@interface CMDocxSection : CMObject

/* Page numbers that the section starts at, typically just one [optional]
 */
@property(nonatomic) NSArray<NSNumber*>* startingPageNumbers;
/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;

@end
