#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxParagraph.h"
@protocol CMDocxParagraph;
@class CMDocxParagraph;



@protocol CMDocxTableCell
@end

@interface CMDocxTableCell : CMObject

/* The index of the cell, 0-based [optional]
 */
@property(nonatomic) NSNumber* cellIndex;
/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* Paragraphs inside the cell; this is where the contents of the cell are stored [optional]
 */
@property(nonatomic) NSArray<CMDocxParagraph>* paragraphs;
/* Color of the cell shading [optional]
 */
@property(nonatomic) NSString* cellShadingColor;
/* Fill of the cell shading [optional]
 */
@property(nonatomic) NSString* cellShadingFill;
/* Pattern of the cell shading [optional]
 */
@property(nonatomic) NSString* cellShadingPattern;
/* Width mode of the cell; can be auto (for automatic) or manual [optional]
 */
@property(nonatomic) NSString* cellWidthMode;
/* Width of the cell [optional]
 */
@property(nonatomic) NSString* cellWidth;

@end
