#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxTableCell.h"
@protocol CMDocxTableCell;
@class CMDocxTableCell;



@protocol CMDocxTableRow
@end

@interface CMDocxTableRow : CMObject

/* Index of the row, 0-based [optional]
 */
@property(nonatomic) NSNumber* rowIndex;
/* The Path of the location of this table row object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* Cells in the row; this is where the contents of the row is stored [optional]
 */
@property(nonatomic) NSArray<CMDocxTableCell>* rowCells;

@end
