#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxTableRow.h"
@protocol CMDocxTableRow;
@class CMDocxTableRow;



@protocol CMDocxTable
@end

@interface CMDocxTable : CMObject

/* The ID of the table; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* tableID;
/* The Path of the location of this table object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* The Width of the table, or 0 if not specified [optional]
 */
@property(nonatomic) NSString* width;
/* The Width configuration type of the table [optional]
 */
@property(nonatomic) NSString* widthType;
/* Rows in the table; this is where the contents is located [optional]
 */
@property(nonatomic) NSArray<CMDocxTableRow>* tableRows;
/* Type for the top border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* topBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* topBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* topBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* topBorderColor;
/* Type for the bottom border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* bottomBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* bottomBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* bottomBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* bottomBorderColor;
/* Type for the left border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* leftBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* leftBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* leftBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* leftBorderColor;
/* Type for the right border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* rightBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* rightBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* rightBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* rightBorderColor;
/* Type for the cell horizontal border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* cellHorizontalBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* cellHorizontalBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* cellHorizontalBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* cellHorizontalBorderColor;
/* Type for the cell vertical border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* cellVerticalBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* cellVerticalBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* cellVerticalBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* cellVerticalBorderColor;
/* Type for the start border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* startBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* startBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* startBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* startBorderColor;
/* Type for the end border - can be a Single, DashDotStroked, Dashed, DashSmallGap, DotDash, DotDotDash, Dotted, Double, DoubleWave, Inset, Nil, None, Outset, Thick, ThickThinLargeGap, ThickThinMediumGap, ThickThinSmallGap, ThinThickLargeGap, ThinThickMediumGap, ThinThickSmallGap, ThinThickThinLargeGap, ThinThickThinMediumGap, ThinThickThinSmallGap, ThreeDEmboss, ThreeDEngrave, Triple, Wave [optional]
 */
@property(nonatomic) NSString* endBorderType;
/* Width of the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* endBorderSize;
/* Spacing around the border in points (1/72nd of an inch) [optional]
 */
@property(nonatomic) NSNumber* endBorderSpace;
/* HTML-style color hex value (do not include a #) [optional]
 */
@property(nonatomic) NSString* endBorderColor;
/* Table indentation type [optional]
 */
@property(nonatomic) NSString* tableIndentationMode;
/* Table indentation width [optional]
 */
@property(nonatomic) NSNumber* tableIndentationWidth;

@end
