#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxImage.h"
@protocol CMDocxImage;
@class CMDocxImage;



@protocol CMDocxInsertImageRequest
@end

@interface CMDocxInsertImageRequest : CMObject

/* Optional: Bytes of the input file to operate on [optional]
 */
@property(nonatomic) NSData* inputDocumentFileBytes;
/* Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). [optional]
 */
@property(nonatomic) NSString* inputDocumentFileUrl;
/* Optional: Bytes of the input image file to operate on; if you supply this value do not supply InputImageFileUrl or ImageToAdd. [optional]
 */
@property(nonatomic) NSData* inputImageFileBytes;
/* Optional: URL of an image file to operate on as input; if you supply this value do not supply InputImageFileBytes or ImageToAdd.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). [optional]
 */
@property(nonatomic) NSString* inputImageFileUrl;
/* Optional: Image to add; if you supply in this object, do not supply InputImageFileBytes or InputImageFileUrl. [optional]
 */
@property(nonatomic) CMDocxImage* imageToAdd;
/* Optional; default is DocumentEnd.  Placement Type of the insert; possible values are: DocumentStart (very beginning of the document), DocumentEnd (very end of the document), BeforeExistingObject (right before an existing object - fill in the InsertPath field using the Path value from an existing object), AfterExistingObject (right after an existing object - fill in the InsertPath field using the Path value from an existing object) [optional]
 */
@property(nonatomic) NSString* insertPlacement;
/* Optional; location within the document to insert the object; fill in the InsertPath field using the Path value from an existing object.  Used with InsertPlacement of BeforeExistingObject or AfterExistingObject [optional]
 */
@property(nonatomic) NSString* insertPath;
/* Optional: The width of the image in EMUs [optional]
 */
@property(nonatomic) NSNumber* widthInEMUs;
/* Optional: The height of the image in EMUs [optional]
 */
@property(nonatomic) NSNumber* heightInEMUs;

@end
