#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxCellStyle
@end

@interface CMDocxCellStyle : CMObject

/* The Path of the location of this object; leave blank for new rows [optional]
 */
@property(nonatomic) NSString* path;
/* Name of the style [optional]
 */
@property(nonatomic) NSString* name;
/* Format ID of the cell style [optional]
 */
@property(nonatomic) NSNumber* formatID;
/* Built=in ID of the cell style [optional]
 */
@property(nonatomic) NSNumber* builtInID;

@end
