#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxTemplateOperation
@end

@interface CMDocxTemplateOperation : CMObject

/* Operation action to take; possible values are \"Replace\" [optional]
 */
@property(nonatomic) NSNumber* action;
/* For Replace operations, the string to match against (to be replaced with ReplaceWith string) [optional]
 */
@property(nonatomic) NSString* matchAgainst;
/* For Replace operations, the string to Replace the original string with [optional]
 */
@property(nonatomic) NSString* replaceWith;

@end
