#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxMetadataCustomProperty
@end

@interface CMDocxMetadataCustomProperty : CMObject

/* Name of the property [optional]
 */
@property(nonatomic) NSString* propertyName;
/* Data type of the property; possible values are \"string\", \"integer\", \"double\" or \"date\" [optional]
 */
@property(nonatomic) NSString* propertyDataType;
/* If the property is of a string data type, then provides the string value if available [optional]
 */
@property(nonatomic) NSString* stringValue;
/* If the property is of a integer data type, then provides the integer value if available [optional]
 */
@property(nonatomic) NSNumber* integerValue;
/* If the property is of a double floating point data type, then provides the double value if available [optional]
 */
@property(nonatomic) NSNumber* doubleValue;
/* If the property is of a date time data type, then provides the date time value if available [optional]
 */
@property(nonatomic) NSDate* dateValue;

@end
