#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxComment.h"
@protocol CMDocxComment;
@class CMDocxComment;



@protocol CMDocxTopLevelComment
@end

@interface CMDocxTopLevelComment : CMObject

/* Path to the comment in the document [optional]
 */
@property(nonatomic) NSString* path;
/* Author name of the comment [optional]
 */
@property(nonatomic) NSString* author;
/* Initials of the author of the comment [optional]
 */
@property(nonatomic) NSString* authorInitials;
/* Text content of the comment [optional]
 */
@property(nonatomic) NSString* commentText;
/* Date timestamp of the comment [optional]
 */
@property(nonatomic) NSDate* commentDate;
/* Child comments, that are replies to this one [optional]
 */
@property(nonatomic) NSArray<CMDocxComment>* replyChildComments;
/* True if this comment is marked as Done in Word, otherwise it is false [optional]
 */
@property(nonatomic) NSNumber* done;

@end
