#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxComment
@end

@interface CMDocxComment : CMObject

/* Path to the comment in the document [optional]
 */
@property(nonatomic) NSString* path;
/* Author name of the comment [optional]
 */
@property(nonatomic) NSString* author;
/* Initials of the author of the comment [optional]
 */
@property(nonatomic) NSString* authorInitials;
/* Text content of the comment [optional]
 */
@property(nonatomic) NSString* commentText;
/* Date timestamp of the comment [optional]
 */
@property(nonatomic) NSDate* commentDate;
/* True if the comment is at the top level, false if this comment is a child reply of another comment [optional]
 */
@property(nonatomic) NSNumber* isTopLevel;
/* True if this comment is a reply to another comment, false otherwise [optional]
 */
@property(nonatomic) NSNumber* isReply;
/* Path to the parent of this comment, if this comment is a reply, otherwise this value will be null [optional]
 */
@property(nonatomic) NSString* parentCommentPath;
/* True if this comment is marked as Done in Word, otherwise it is false [optional]
 */
@property(nonatomic) NSNumber* done;

@end
