#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocumentValidationError.h"
@protocol CMDocumentValidationError;
@class CMDocumentValidationError;



@protocol CMDocumentValidationResult
@end

@interface CMDocumentValidationResult : CMObject

/* True if the document is valid and has no errors, false otherwise [optional]
 */
@property(nonatomic) NSNumber* documentIsValid;
/* Number of validation errors found in the document [optional]
 */
@property(nonatomic) NSNumber* errorCount;
/* Number of validation warnings found in the document [optional]
 */
@property(nonatomic) NSNumber* warningCount;
/* Details of errors and warnings found [optional]
 */
@property(nonatomic) NSArray<CMDocumentValidationError>* errorsAndWarnings;

@end
