#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxText.h"
@protocol CMDocxText;
@class CMDocxText;



@protocol CMDocxRun
@end

@interface CMDocxRun : CMObject

/* Index of the run, 0-based [optional]
 */
@property(nonatomic) NSNumber* runIndex;
/* The Path of the location of this Run object; leave blank for creation [optional]
 */
@property(nonatomic) NSString* path;
/* Text items inside the run; this is where the actual text content is stored [optional]
 */
@property(nonatomic) NSArray<CMDocxText>* textItems;
/* True to make the text bold, false otherwise [optional]
 */
@property(nonatomic) NSNumber* bold;
/* True to make the text italic, false otherwise [optional]
 */
@property(nonatomic) NSNumber* italic;
/* Underline mode for the text; possible values are: Words, Double, Thick, Dotted, DottedHeavy, Dash, DashedHeavy, DashLong, DashLongHeavy, DotDash, DashDotHeavy, DotDotDash, DashDotDotHeavy, Wave, WavyHeavy, WavyDouble, None [optional]
 */
@property(nonatomic) NSString* underline;
/* Font Family name for the text, e.g. \"Arial\" or \"Times New Roman\" [optional]
 */
@property(nonatomic) NSString* fontFamily;
/* Font size in font points (e.g. \"24\") [optional]
 */
@property(nonatomic) NSString* fontSize;

@end
