#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMDocxImage
@end

@interface CMDocxImage : CMObject

/* The Path of the location of this object; leave blank for new tables [optional]
 */
@property(nonatomic) NSString* path;
/* The Name of the image [optional]
 */
@property(nonatomic) NSString* imageName;
/* The Id of the image [optional]
 */
@property(nonatomic) NSNumber* imageId;
/* The Description of the image [optional]
 */
@property(nonatomic) NSString* imageDescription;
/* Width of the image in EMUs (English Metric Units); set to 0 to default to page width and aspect-ratio based height [optional]
 */
@property(nonatomic) NSNumber* imageWidth;
/* Height of the image in EMUs (English Metric Units); set to 0 to default to page width and aspect-ratio based height [optional]
 */
@property(nonatomic) NSNumber* imageHeight;
/* X (horizontal) offset of the image [optional]
 */
@property(nonatomic) NSNumber* xOffset;
/* Y (vertical) offset of the image [optional]
 */
@property(nonatomic) NSNumber* yOffset;
/* Read-only; internal ID for the image contents [optional]
 */
@property(nonatomic) NSString* imageDataEmbedId;
/* Read-only; image data MIME content-type [optional]
 */
@property(nonatomic) NSString* imageDataContentType;
/* Read-only; internal file name/path for the image [optional]
 */
@property(nonatomic) NSString* imageInternalFileName;
/* URL to the image contents; file is stored in an in-memory cache and will be deleted.  Call Finish-Editing to get the contents. [optional]
 */
@property(nonatomic) NSString* imageContentsURL;
/* True if the image is inline with the text; false if it is floating [optional]
 */
@property(nonatomic) NSNumber* inlineWithText;

@end
