#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMEmlAttachment.h"
@protocol CMEmlAttachment;
@class CMEmlAttachment;



@protocol CMEmlToHtmlResult
@end

@interface CMEmlToHtmlResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* An HTML string version of the EML file [optional]
 */
@property(nonatomic) NSString* content;
/* The main body of the EML file's email as an HTML string [optional]
 */
@property(nonatomic) NSString* body;
/* The From sender of the EML file's email [optional]
 */
@property(nonatomic) NSString* from;
/* The To recipients of the EML file's email [optional]
 */
@property(nonatomic) NSString* to;
/* The CC recipients of the EML file's email [optional]
 */
@property(nonatomic) NSString* cc;
/* The date and time that the EML file's email was sent [optional]
 */
@property(nonatomic) NSString* dateSent;
/* The subject of the EML file's email [optional]
 */
@property(nonatomic) NSString* subject;
/* List of all attachments for the EML file [optional]
 */
@property(nonatomic) NSArray<CMEmlAttachment>* attachments;

@end
