#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFindStringRegexRequest
@end

@interface CMFindStringRegexRequest : CMObject

/* Input text content [optional]
 */
@property(nonatomic) NSString* textContent;
/* Target input regular expression (regex) to find [optional]
 */
@property(nonatomic) NSString* targetRegex;
/* Set to True to match case, False to ignore case [optional]
 */
@property(nonatomic) NSNumber* matchCase;

@end
