#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMFindRegexMatch.h"
@protocol CMFindRegexMatch;
@class CMFindRegexMatch;



@protocol CMFindStringRegexResponse
@end

@interface CMFindStringRegexResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Regular expression matches [optional]
 */
@property(nonatomic) NSArray<CMFindRegexMatch>* matches;
/* The number of matches [optional]
 */
@property(nonatomic) NSNumber* matchCount;

@end
