#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFindStringSimpleRequest
@end

@interface CMFindStringSimpleRequest : CMObject

/* Input text content [optional]
 */
@property(nonatomic) NSString* textContent;
/* Target input string to find [optional]
 */
@property(nonatomic) NSString* targetString;

@end
