#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxParagraph.h"
@protocol CMDocxParagraph;
@class CMDocxParagraph;



@protocol CMFindDocxParagraphResponse
@end

@interface CMFindDocxParagraphResponse : CMObject

/* True if successful; false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Matching paragraphs [optional]
 */
@property(nonatomic) NSArray<CMDocxParagraph>* matchingParagraphs;
/* Count of matching paragraphs [optional]
 */
@property(nonatomic) NSNumber* count;

@end
