#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFinishEditingRequest
@end

@interface CMFinishEditingRequest : CMObject

/* URL of a document being edited to get the contents of. [optional]
 */
@property(nonatomic) NSString* inputFileUrl;

@end
