#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMFindStringMatch
@end

@interface CMFindStringMatch : CMObject

/* 0-based index of the start of the match [optional]
 */
@property(nonatomic) NSNumber* characterOffsetStart;
/* 0-based index of the end of the match [optional]
 */
@property(nonatomic) NSNumber* characterOffsetEnd;
/* Text content of the line containing the match [optional]
 */
@property(nonatomic) NSString* containingLine;

@end
