#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxPage.h"
@protocol CMDocxPage;
@class CMDocxPage;



@protocol CMGetDocxPagesResponse
@end

@interface CMGetDocxPagesResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Pages in the document [optional]
 */
@property(nonatomic) NSArray<CMDocxPage>* pages;
/* Count of pages [optional]
 */
@property(nonatomic) NSNumber* pageCount;

@end
