#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMExifValue.h"
@protocol CMExifValue;
@class CMExifValue;



@protocol CMGetImageInfoResult
@end

@interface CMGetImageInfoResult : CMObject


@property(nonatomic) NSNumber* successful;
/* Color space of the image [optional]
 */
@property(nonatomic) NSString* colorSpace;
/* Color type of the image [optional]
 */
@property(nonatomic) NSString* colorType;
/* Width in pixels of the image [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height in pixels of the image [optional]
 */
@property(nonatomic) NSNumber* height;
/* Compression level value from 0 (lowest quality) to 100 (highest quality) [optional]
 */
@property(nonatomic) NSNumber* compressionLevel;
/* SHA256 hash signature of the image [optional]
 */
@property(nonatomic) NSString* imageHashSignature;
/* True if the image contains transparency, otherwise false [optional]
 */
@property(nonatomic) NSNumber* hasTransparency;
/* MIME type of the image format [optional]
 */
@property(nonatomic) NSString* mimeType;
/* Image format [optional]
 */
@property(nonatomic) NSString* imageFormat;
/* Units of the DPI measurement; can be either in Inches or Centimeters [optional]
 */
@property(nonatomic) NSString* dPIUnit;
/* DPI (pixels per unit, e.g. pixels per inch) of the image [optional]
 */
@property(nonatomic) NSNumber* dPI;
/* Unique colors in the image [optional]
 */
@property(nonatomic) NSNumber* colorCount;
/* Bit depth of the image [optional]
 */
@property(nonatomic) NSNumber* bitDepth;
/* Comment string in the image [optional]
 */
@property(nonatomic) NSString* comment;
/* Name of the EXIF profile used [optional]
 */
@property(nonatomic) NSString* exifProfileName;
/* EXIF tags and values embedded in the image [optional]
 */
@property(nonatomic) NSArray<CMExifValue>* exifValues;

@end
