#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxMetadataCustomProperty.h"
@protocol CMDocxMetadataCustomProperty;
@class CMDocxMetadataCustomProperty;



@protocol CMGetDocxMetadataPropertiesResponse
@end

@interface CMGetDocxMetadataPropertiesResponse : CMObject

/* Name of the Company that authored the document, if available [optional]
 */
@property(nonatomic) NSString* company;
/* Name of the Manager that authored the document, if available [optional]
 */
@property(nonatomic) NSString* manager;
/* Application version that authored the document, if available [optional]
 */
@property(nonatomic) NSString* applicationVersion;
/* Word count of the document [optional]
 */
@property(nonatomic) NSNumber* wordCount;
/* Line count of the document [optional]
 */
@property(nonatomic) NSNumber* lineCount;
/* Paragraph count of the document [optional]
 */
@property(nonatomic) NSNumber* paragraphCount;
/* Page count of the document [optional]
 */
@property(nonatomic) NSNumber* pageCount;
/* Custom properties applied to the document [optional]
 */
@property(nonatomic) NSArray<CMDocxMetadataCustomProperty>* customProperties;
/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;

@end
