#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMXlsxSpreadsheetColumn.h"
@protocol CMXlsxSpreadsheetColumn;
@class CMXlsxSpreadsheetColumn;



@protocol CMGetXlsxColumnsResponse
@end

@interface CMGetXlsxColumnsResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Spreadsheet Columns in the XLSX document [optional]
 */
@property(nonatomic) NSArray<CMXlsxSpreadsheetColumn>* columns;

@end
