#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMGetFileTypeIconResult
@end

@interface CMGetFileTypeIconResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* PNG icon as a byte array [optional]
 */
@property(nonatomic) NSData* icon;
/* Extension used for the icon [optional]
 */
@property(nonatomic) NSString* extension;

@end
