#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMPdfAnnotation.h"
@protocol CMPdfAnnotation;
@class CMPdfAnnotation;



@protocol CMGetPdfAnnotationsResult
@end

@interface CMGetPdfAnnotationsResult : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Annotations in the PDF file, ordered by placement from start to finish in the document [optional]
 */
@property(nonatomic) NSArray<CMPdfAnnotation>* annotations;

@end
