#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxImage.h"
@protocol CMDocxImage;
@class CMDocxImage;



@protocol CMGetDocxImagesResponse
@end

@interface CMGetDocxImagesResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Images in the DOCX document [optional]
 */
@property(nonatomic) NSArray<CMDocxImage>* images;

@end
