#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxTable.h"
@protocol CMDocxTable;
@class CMDocxTable;



@protocol CMGetDocxTableByIndexResponse
@end

@interface CMGetDocxTableByIndexResponse : CMObject

/* True if successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Requested Table in the DOCX file [optional]
 */
@property(nonatomic) CMDocxTable* table;

@end
