#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMHtmlToPngRequest
@end

@interface CMHtmlToPngRequest : CMObject

/* HTML to render to PNG (screenshot) [optional]
 */
@property(nonatomic) NSString* html;
/* Optional: Additional number of milliseconds to wait once the web page has finished loading before taking the screenshot.  Can be helpful for highly asynchronous websites. Provide a value of 0 for the default of 5000 milliseconds (5 seconds). Maximum is 30000 milliseconds (30 seconds). [optional]
 */
@property(nonatomic) NSNumber* extraLoadingWait;
/* Optional: Width of the screenshot in pixels; supply 0 to default to 1280 x 1024, supply -1 to measure the full screen height of the page and attempt to take a screen-height screenshot [optional]
 */
@property(nonatomic) NSNumber* screenshotWidth;
/* Optional: Height of the screenshot in pixels; supply 0 to default to 1280 x 1024, supply -1 to measure the full screen height of the page and attempt to take a screen-height screenshot [optional]
 */
@property(nonatomic) NSNumber* screenshotHeight;

@end
