#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMHtmlToPdfRequest
@end

@interface CMHtmlToPdfRequest : CMObject

/* HTML to render to PDF [optional]
 */
@property(nonatomic) NSString* html;
/* Optional: Additional number of milliseconds to wait once the web page has finished loading before taking the screenshot.  Can be helpful for highly asynchronous websites. Provide a value of 0 for the default of 5000 milliseconds (5 seconds). Maximum is 30000 milliseconds (30 seconds). [optional]
 */
@property(nonatomic) NSNumber* extraLoadingWait;
/* Optional: Set to true to include background graphics in the PDF, or false to not include.  Default is true. [optional]
 */
@property(nonatomic) NSNumber* includeBackgroundGraphics;
/* Optional: Set to 100 to scale at 100%, set to 50% to scale down to 50% scale, set to 200% to scale up to 200% scale, etc.  Default is 100%. Maximum is 1000%. [optional]
 */
@property(nonatomic) NSNumber* scaleFactor;

@end
