#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMHtmlTemplateOperation.h"
@protocol CMHtmlTemplateOperation;
@class CMHtmlTemplateOperation;



@protocol CMHtmlTemplateApplicationRequest
@end

@interface CMHtmlTemplateApplicationRequest : CMObject


@property(nonatomic) NSString* htmlTemplate;

@property(nonatomic) NSString* htmlTemplateUrl;

@property(nonatomic) NSArray<CMHtmlTemplateOperation>* operations;

@end
