#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMHtmlTemplateOperation.h"
@protocol CMHtmlTemplateOperation;
@class CMHtmlTemplateOperation;



@protocol CMHtmlTemplateApplicationRequest
@end

@interface CMHtmlTemplateApplicationRequest : CMObject

/* HTML template input as a string [optional]
 */
@property(nonatomic) NSString* htmlTemplate;
/* URL to HTML template input [optional]
 */
@property(nonatomic) NSString* htmlTemplateUrl;
/* Operations to apply to this template [optional]
 */
@property(nonatomic) NSArray<CMHtmlTemplateOperation>* operations;

@end
