#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMHtmlMdResult
@end

@interface CMHtmlMdResult : CMObject

/* True if operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Resulting HTML from the conversion [optional]
 */
@property(nonatomic) NSString* html;

@end
