#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMDocxTableRow.h"
@protocol CMDocxTableRow;
@class CMDocxTableRow;



@protocol CMInsertDocxTableRowRequest
@end

@interface CMInsertDocxTableRowRequest : CMObject

/* Optional: Bytes of the input file to operate on [optional]
 */
@property(nonatomic) NSData* inputFileBytes;
/* Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). [optional]
 */
@property(nonatomic) NSString* inputFileUrl;
/* Table you would like to insert [optional]
 */
@property(nonatomic) CMDocxTableRow* rowToInsert;
/* Optional; default is TableEnd.  Placement Type of the insert; possible values are: TableStart (very beginning of the table), TableEnd (very end of the document), or a 0-based row index number as an integer, 0 being the first row in the table, 1 being the second row in the table, 2 being the third row in the table, etc. to insert this row after [optional]
 */
@property(nonatomic) NSString* insertPlacement;
/* Required; the path to the existing table to modify [optional]
 */
@property(nonatomic) NSString* existingTablePath;

@end
