#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMMsgAttachment.h"
@protocol CMMsgAttachment;
@class CMMsgAttachment;



@protocol CMMsgToHtmlResult
@end

@interface CMMsgToHtmlResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* An HTML string version of the MSG file [optional]
 */
@property(nonatomic) NSString* content;
/* The main body of the MSG file's email as an HTML string [optional]
 */
@property(nonatomic) NSString* body;
/* The From sender of the MSG file's email [optional]
 */
@property(nonatomic) NSString* from;
/* The To recipients of the MSG file's email [optional]
 */
@property(nonatomic) NSString* to;
/* The CC recipients of the MSG file's email [optional]
 */
@property(nonatomic) NSString* cc;
/* The time that the MSG file's email was received [optional]
 */
@property(nonatomic) NSString* receivedTime;
/* The subject of the MSG file's email [optional]
 */
@property(nonatomic) NSString* subject;
/* List of all attachments for the MSG file [optional]
 */
@property(nonatomic) NSArray<CMMsgAttachment>* attachments;

@end
