#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMPageConversionResult.h"
@protocol CMPageConversionResult;
@class CMPageConversionResult;



@protocol CMMultipageImageFormatConversionResult
@end

@interface CMMultipageImageFormatConversionResult : CMObject


@property(nonatomic) NSNumber* successful;

@property(nonatomic) NSNumber* pageCount;

@property(nonatomic) NSArray<CMPageConversionResult>* pages;

@end
