#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPdfAnnotation
@end

@interface CMPdfAnnotation : CMObject

/* Title of the annotation; this is often the author of the annotation in Acrobat-created PDF files [optional]
 */
@property(nonatomic) NSString* title;
/* Type of the annotation; possible values are Text [optional]
 */
@property(nonatomic) NSString* annotationType;
/* The 1-based index of the page containing the annotation [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* The 0-based index of the annotation in the document [optional]
 */
@property(nonatomic) NSNumber* annotationIndex;
/* Subject of the annotation [optional]
 */
@property(nonatomic) NSString* subject;
/* Text contents of the annotation [optional]
 */
@property(nonatomic) NSString* textContents;
/* Date that the annotation was created [optional]
 */
@property(nonatomic) NSDate* creationDate;
/* Date that the annotation was last modified [optional]
 */
@property(nonatomic) NSDate* modifiedDate;
/* Left X coordinate for the location of the annotation [optional]
 */
@property(nonatomic) NSNumber* leftX;
/* Top Y coordination of the location of the annotation [optional]
 */
@property(nonatomic) NSNumber* topY;
/* Width of the annotation [optional]
 */
@property(nonatomic) NSNumber* width;
/* Height of the annotation [optional]
 */
@property(nonatomic) NSNumber* height;

@end
