#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPdfPageText
@end

@interface CMPdfPageText : CMObject

/* Page number of the page (1-based) [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* Text of the page [optional]
 */
@property(nonatomic) NSString* pageText;

@end
