#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPdfDocument
@end

@interface CMPdfDocument : CMObject

/* Page number of the converted page, starting with 1 for the first page [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* URL to the PDF file of this worksheet; file is stored in an in-memory cache and will be deleted [optional]
 */
@property(nonatomic) NSString* uRL;
/* If returnDocumentContents is set to true, will contain the contents of the document; otherwise will be set to null and the document contents will be available via the URL parameter [optional]
 */
@property(nonatomic) NSData* documentContents;

@end
