#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPdfMetadata
@end

@interface CMPdfMetadata : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Title of the document [optional]
 */
@property(nonatomic) NSString* title;
/* Keywords of the document [optional]
 */
@property(nonatomic) NSString* keywords;
/* Subject of the document [optional]
 */
@property(nonatomic) NSString* subject;
/* User name of the creator/author of the document, if available, null if not available [optional]
 */
@property(nonatomic) NSString* author;
/* Creator of the document [optional]
 */
@property(nonatomic) NSString* creator;
/* The timestamp that the document was last modified, if available, null if not available [optional]
 */
@property(nonatomic) NSDate* dateModified;
/* The timestamp that the document was created, if available, null if not available [optional]
 */
@property(nonatomic) NSDate* dateCreated;
/* The number of pages in the document [optional]
 */
@property(nonatomic) NSNumber* pageCount;

@end
