#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMPresentationResult
@end

@interface CMPresentationResult : CMObject

/* Worksheet number of the converted page, starting with 1 for the left-most worksheet [optional]
 */
@property(nonatomic) NSNumber* slideNumber;
/* URL to the PPTX file of this slide; file is stored in an in-memory cache and will be deleted [optional]
 */
@property(nonatomic) NSString* uRL;
/* Contents of the presentation in bytes [optional]
 */
@property(nonatomic) NSData* presentationContents;

@end
