#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMRemoveWhitespaceFromTextRequest
@end

@interface CMRemoveWhitespaceFromTextRequest : CMObject

/* Input text string to remove the whitespace from [optional]
 */
@property(nonatomic) NSString* textContainingWhitespace;

@end
