#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMReplaceStringRegexRequest
@end

@interface CMReplaceStringRegexRequest : CMObject

/* Input text content [optional]
 */
@property(nonatomic) NSString* textContent;
/* Target input regular expression (regex) string to match and be replaced; supports all regular expression values [optional]
 */
@property(nonatomic) NSString* regularExpressionString;
/* Replacement for target string; supports referencing indexed regex matched values from RegularExpressionString, such as $1, $2, and so on [optional]
 */
@property(nonatomic) NSString* replaceWithString;

@end
