#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMReplaceStringRequest
@end

@interface CMReplaceStringRequest : CMObject

/* Optional: Bytes of the input file to operate on [optional]
 */
@property(nonatomic) NSData* inputFileBytes;
/* Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). [optional]
 */
@property(nonatomic) NSString* inputFileUrl;
/* String to search for and match against, to be replaced [optional]
 */
@property(nonatomic) NSString* matchString;
/* String to replace the matched values with [optional]
 */
@property(nonatomic) NSString* replaceString;
/* True if the case should be matched, false for case insensitive match [optional]
 */
@property(nonatomic) NSNumber* matchCase;

@end
