#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMSetFormFieldValue.h"
@protocol CMSetFormFieldValue;
@class CMSetFormFieldValue;



@protocol CMSetPdfFormFieldsRequest
@end

@interface CMSetPdfFormFieldsRequest : CMObject

/* Field values to set [optional]
 */
@property(nonatomic) NSArray<CMSetFormFieldValue>* fieldValues;
/* Contents of the input file to set the fields on [optional]
 */
@property(nonatomic) NSData* inputFileBytes;

@end
