#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSetFormFieldValue
@end

@interface CMSetFormFieldValue : CMObject

/* Name of the field to set; you can call /convert/edit/pdf/form/get-fields to enumerate field names in a form [optional]
 */
@property(nonatomic) NSString* fieldName;
/* For fields of type Text, the text value to put into the field [optional]
 */
@property(nonatomic) NSString* textValue;
/* For fields of type Checkbox, the value to put into the field [optional]
 */
@property(nonatomic) NSNumber* checkboxValue;
/* For fields of type ComboBox; specifies the selected index of the combo box selection [optional]
 */
@property(nonatomic) NSNumber* comboBoxSelectedIndex;

@end
