#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMPdfMetadata.h"
@protocol CMPdfMetadata;
@class CMPdfMetadata;



@protocol CMSetPdfMetadataRequest
@end

@interface CMSetPdfMetadataRequest : CMObject

/* Input file contents bytes for the file to modify [optional]
 */
@property(nonatomic) NSData* inputFileBytes;
/* PDF metadata to set on the file [optional]
 */
@property(nonatomic) CMPdfMetadata* metadataToSet;

@end
