#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSingleReplaceString
@end

@interface CMSingleReplaceString : CMObject

/* String to search for and match against, to be replaced [optional]
 */
@property(nonatomic) NSString* matchString;
/* String to replace the matched values with [optional]
 */
@property(nonatomic) NSString* replaceString;
/* True if the case should be matched, false for case insensitive match [optional]
 */
@property(nonatomic) NSNumber* matchCase;

@end
