#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMSplitDocumentResult
@end

@interface CMSplitDocumentResult : CMObject

/* Page number of the converted page, starting with 1 for the first page [optional]
 */
@property(nonatomic) NSNumber* pageNumber;
/* URL to the DOCX file of this slide; file is stored in an in-memory cache and will be deleted [optional]
 */
@property(nonatomic) NSString* uRL;
/* Contents of the document in bytes [optional]
 */
@property(nonatomic) NSData* documentContents;

@end
