#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMTextDocumentLine.h"
@protocol CMTextDocumentLine;
@class CMTextDocumentLine;



@protocol CMSplitTextDocumentByLinesResult
@end

@interface CMSplitTextDocumentByLinesResult : CMObject


@property(nonatomic) NSArray<CMTextDocumentLine>* resultLines;
/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* The count of lines in the text file [optional]
 */
@property(nonatomic) NSNumber* lineCount;

@end
