#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMTextDocumentElement.h"
@protocol CMTextDocumentElement;
@class CMTextDocumentElement;



@protocol CMSplitTextDocumentByStringResult
@end

@interface CMSplitTextDocumentByStringResult : CMObject


@property(nonatomic) NSArray<CMTextDocumentElement>* resultElements;
/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* The count of elements in the text file [optional]
 */
@property(nonatomic) NSNumber* elementCount;

@end
