#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMThumbnail
@end

@interface CMThumbnail : CMObject

/* Index of this thumbnail [optional]
 */
@property(nonatomic) NSNumber* index;
/* A PNG thumbnail of the document page [optional]
 */
@property(nonatomic) NSData* content;

@end
