#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMWorksheetResult
@end

@interface CMWorksheetResult : CMObject

/* Worksheet number of the converted page, starting with 1 for the left-most worksheet [optional]
 */
@property(nonatomic) NSNumber* worksheetNumber;
/* The name of the worksheet [optional]
 */
@property(nonatomic) NSString* worksheetName;
/* URL to the XLSX file of this worksheet; file is stored in an in-memory cache and will be deleted [optional]
 */
@property(nonatomic) NSString* uRL;
/* Contents of the worksheet in bytes [optional]
 */
@property(nonatomic) NSData* worksheetContents;

@end
