#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMXlsxImage
@end

@interface CMXlsxImage : CMObject

/* The Path of the location of this object; leave blank for new rows [optional]
 */
@property(nonatomic) NSString* path;
/* Read-only; internal ID for the image contents [optional]
 */
@property(nonatomic) NSString* imageDataEmbedId;
/* Read-only; image data MIME content-type [optional]
 */
@property(nonatomic) NSString* imageDataContentType;
/* Read-only; internal file name/path for the image [optional]
 */
@property(nonatomic) NSString* imageInternalFileName;
/* URL to the image contents; file is stored in an in-memory cache and will be deleted.  Call Finish-Editing to get the contents. [optional]
 */
@property(nonatomic) NSString* imageContentsURL;

@end
