#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMXlsxSpreadsheetCell
@end

@interface CMXlsxSpreadsheetCell : CMObject

/* The Path of the location of this object; leave blank for new rows [optional]
 */
@property(nonatomic) NSString* path;
/* Text value of the cell [optional]
 */
@property(nonatomic) NSString* textValue;
/* Cell reference of the cell, e.g. A1, Z22, etc. [optional]
 */
@property(nonatomic) NSString* cellIdentifier;
/* Identifier for the style to apply to this style [optional]
 */
@property(nonatomic) NSNumber* styleIndex;

@property(nonatomic) NSString* formula;

@end
