#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "CMXlsxSpreadsheetCell.h"
@protocol CMXlsxSpreadsheetCell;
@class CMXlsxSpreadsheetCell;



@protocol CMXlsxSpreadsheetRow
@end

@interface CMXlsxSpreadsheetRow : CMObject

/* The Path of the location of this object; leave blank for new rows [optional]
 */
@property(nonatomic) NSString* path;
/* Spreadsheet Cells in the spreadsheet row [optional]
 */
@property(nonatomic) NSArray<CMXlsxSpreadsheetCell>* cells;

@end
