#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMXlsxWorksheet
@end

@interface CMXlsxWorksheet : CMObject

/* The Path of the location of this object; leave blank for new worksheets [optional]
 */
@property(nonatomic) NSString* path;
/* User-facing name of the worksheet tab [optional]
 */
@property(nonatomic) NSString* worksheetName;

@end
