#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMXmlRemoveWithXPathResult
@end

@interface CMXmlRemoveWithXPathResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Resulting, modified XML document with matching nodes removed as a string [optional]
 */
@property(nonatomic) NSString* resultingXmlDocument;
/* Matching selected XML nodes as strings [optional]
 */
@property(nonatomic) NSArray<NSString*>* xmlNodesRemoved;
/* Count of the matching results [optional]
 */
@property(nonatomic) NSNumber* nodesRemovedCount;

@end
