#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMXmlFilterWithXPathResult
@end

@interface CMXmlFilterWithXPathResult : CMObject

/* True if the operation was successful, false otherwise [optional]
 */
@property(nonatomic) NSNumber* successful;
/* Matching selected XML nodes as strings [optional]
 */
@property(nonatomic) NSArray<NSString*>* xmlNodes;
/* Count of the matching results [optional]
 */
@property(nonatomic) NSNumber* resultCount;

@end
