#import <Foundation/Foundation.h>
#import "CMObject.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol CMZipEncryptionAdvancedRequest
@end

@interface CMZipEncryptionAdvancedRequest : CMObject

/* Input Zip File archive contents in bytes [optional]
 */
@property(nonatomic) NSData* inputFileContents;
/* Password to place on the Zip file; the longer the password, the more secure [optional]
 */
@property(nonatomic) NSString* password;
/* Encryption algorithm to use; possible values are AES-256 (recommended), AES-128, and PK-Zip (not recommended; legacy, weak encryption algorithm).  Default is AES-256. [optional]
 */
@property(nonatomic) NSString* encryptionAlgorithm;

@end
