#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMConvertDataApi: NSObject <CMApi>

extern NSString* kCMConvertDataApiErrorDomain;
extern NSInteger kCMConvertDataApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// CSV to JSON conversion
/// Convert a CSV file to a JSON object array
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) convertDataCsvToJsonWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// XML to JSON conversion
/// Convert an XML string or file into JSON
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) convertDataXmlToJsonWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
