#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMCompareDocumentApi: NSObject <CMApi>

extern NSString* kCMCompareDocumentApiErrorDomain;
extern NSInteger kCMCompareDocumentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Compare Two Word DOCX
/// Compare two Office Word Documents (docx) files and highlight the differences
///
/// @param inputFile1 First input file to perform the operation on.
/// @param inputFile2 Second input file to perform the operation on (more than 2 can be supplied).
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) compareDocumentDocxWithInputFile1: (NSURL*) inputFile1
    inputFile2: (NSURL*) inputFile2
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
