#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMMergeDocumentApi: NSObject <CMApi>

extern NSString* kCMMergeDocumentApiErrorDomain;
extern NSInteger kCMMergeDocumentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Merge Multple Word DOCX Together
/// Combine multiple Office Word Documents (docx) into one single Office Word document
///
/// @param inputFile1 First input file to perform the operation on.
/// @param inputFile2 Second input file to perform the operation on (more than 2 can be supplied).
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) mergeDocumentDocxWithInputFile1: (NSURL*) inputFile1
    inputFile2: (NSURL*) inputFile2
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Merge Multple PDF Files Together
/// Combine multiple PDF files (pdf) into a single PDF document, preserving the order of the input documents in the combined document
///
/// @param inputFile1 First input file to perform the operation on.
/// @param inputFile2 Second input file to perform the operation on (more than 2 can be supplied).
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) mergeDocumentPdfWithInputFile1: (NSURL*) inputFile1
    inputFile2: (NSURL*) inputFile2
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Merge Multple PowerPoint PPTX Together
/// Combine multiple Office PowerPoint presentations (pptx) into one single Office PowerPoint presentation
///
/// @param inputFile1 First input file to perform the operation on.
/// @param inputFile2 Second input file to perform the operation on (more than 2 can be supplied).
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) mergeDocumentPptxWithInputFile1: (NSURL*) inputFile1
    inputFile2: (NSURL*) inputFile2
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Merge Multple Excel XLSX Together
/// Combine multiple Office Excel spreadsheets (xlsx) into a single Office Excel spreadsheet
///
/// @param inputFile1 First input file to perform the operation on.
/// @param inputFile2 Second input file to perform the operation on (more than 2 can be supplied).
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) mergeDocumentXlsxWithInputFile1: (NSURL*) inputFile1
    inputFile2: (NSURL*) inputFile2
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
