#import <Foundation/Foundation.h>
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMTransformDocumentApi: NSObject <CMApi>

extern NSString* kCMTransformDocumentApiErrorDomain;
extern NSInteger kCMTransformDocumentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Replace string in Word DOCX document
/// Replace all instances of a string in an Office Word Document (docx)
///
/// @param matchString String to search for and match against, to be replaced
/// @param replaceString String to replace the matched values with
/// @param inputFile Optional: Input file to perform the operation on. (optional)
/// @param inputFileUrl Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API (part of EditDocumentApi) to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). (optional)
/// @param matchCase Optional: True if the case should be matched, false for case insensitive match. Default is false. (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) transformDocumentDocxReplaceWithMatchString: (NSString*) matchString
    replaceString: (NSString*) replaceString
    inputFile: (NSURL*) inputFile
    inputFileUrl: (NSString*) inputFileUrl
    matchCase: (NSNumber*) matchCase
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;


/// Replace string in PowerPoint PPTX presentation
/// Replace all instances of a string in an Office PowerPoint Document (pptx)
///
/// @param matchString String to search for and match against, to be replaced
/// @param replaceString String to replace the matched values with
/// @param inputFile Optional: Input file to perform the operation on. (optional)
/// @param inputFileUrl Optional: URL of a file to operate on as input.  This can be a public URL, or you can also use the begin-editing API (part of EditDocumentApi) to upload a document and pass in the secure URL result from that operation as the URL here (this URL is not public). (optional)
/// @param matchCase Optional: True if the case should be matched, false for case insensitive match. Default is false. (optional)
/// 
///  code:200 message:"OK"
///
/// @return NSData*
-(NSURLSessionTask*) transformDocumentPptxReplaceWithMatchString: (NSString*) matchString
    replaceString: (NSString*) replaceString
    inputFile: (NSURL*) inputFile
    inputFileUrl: (NSString*) inputFileUrl
    matchCase: (NSNumber*) matchCase
    completionHandler: (void (^)(NSData* output, NSError* error)) handler;



@end
