#import <Foundation/Foundation.h>
#import "CMDocumentValidationResult.h"
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMValidateDocumentApi: NSObject <CMApi>

extern NSString* kCMValidateDocumentApiErrorDomain;
extern NSInteger kCMValidateDocumentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Validate a Word document (DOCX)
/// Validate a Word document (DOCX); if the document is not valid, identifies the errors in the document
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return CMDocumentValidationResult*
-(NSURLSessionTask*) validateDocumentDocxValidationWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMDocumentValidationResult* output, NSError* error)) handler;


/// Validate a PowerPoint presentation (PPTX)
/// Validate a PowerPoint presentation (PPTX); if the document is not valid, identifies the errors in the document
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return CMDocumentValidationResult*
-(NSURLSessionTask*) validateDocumentPptxValidationWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMDocumentValidationResult* output, NSError* error)) handler;


/// Validate a Excel document (XLSX)
/// Validate a Excel document (XLSX); if the document is not valid, identifies the errors in the document
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return CMDocumentValidationResult*
-(NSURLSessionTask*) validateDocumentXlsxValidationWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMDocumentValidationResult* output, NSError* error)) handler;



@end
