#import <Foundation/Foundation.h>
#import "CMCreateZipArchiveRequest.h"
#import "CMZipExtractResponse.h"
#import "CMApi.h"

/**
* convertapi
* Convert API lets you effortlessly convert file formats and types.
*
* OpenAPI spec version: v1
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface CMZipArchiveApi: NSObject <CMApi>

extern NSString* kCMZipArchiveApiErrorDomain;
extern NSInteger kCMZipArchiveApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(CMApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Compress files to create a new zip archive
/// Create a new zip archive by compressing input files.
///
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) zipArchiveZipCreateWithCompletionHandler: 
    (void (^)(NSObject* output, NSError* error)) handler;


/// Compress files and folders to create a new zip archive with advanced options
/// Create a new zip archive by compressing input files, folders and leverage advanced options to control the structure of the resulting zip archive.
///
/// @param request Input request
/// 
///  code:200 message:"OK"
///
/// @return NSObject*
-(NSURLSessionTask*) zipArchiveZipCreateAdvancedWithRequest: (CMCreateZipArchiveRequest*) request
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;


/// Extract, decompress files and folders from a zip archive
/// Extracts a zip archive by decompressing files, and folders.
///
/// @param inputFile Input file to perform the operation on.
/// 
///  code:200 message:"OK"
///
/// @return CMZipExtractResponse*
-(NSURLSessionTask*) zipArchiveZipExtractWithInputFile: (NSURL*) inputFile
    completionHandler: (void (^)(CMZipExtractResponse* output, NSError* error)) handler;



@end
